# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RrRFz9mYYJu_oRMQWTcsCeFyGONmzECI
"""

score_strings = input().split()

failed_count = 0

for score_str in score_strings:

    score = int(score_str)

    if score < 60:

        failed_count += 1

print(failed_count)